/* Generated by bin2c */

extern unsigned char dualboot_install_ipod6g[5332];
extern unsigned char dualboot_install_ipodnano3g[5188];
extern unsigned char dualboot_uninstall_ipod6g[5028];
extern unsigned char dualboot_uninstall_ipodnano3g[4884];
